[package]
name = "block_sampling"
version = "0.0.1"
edition = "2024" 

[dependencies]

Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "testnet" }

[addresses]
block_sampling = "0x0"